[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Odoo Cloudcommerce connector by Kitworks"
authors = [{name = "Kitworks", email = "info@kitworks.systems"}]
dynamic = ["version", "description"]
